### ISSUE TITLE
The name of the SOC folder should be SRC?

### ISSUE THREAD

**Issue by obaica** [shahramyalameha/ElATools#1]
The name of the SOC folder should be SRC?

You mentioned "Then Go into ElATools_SRC/src directory". But I don’t see the SRC folder.

**Comment by shahramyalameha** [comment]
Thanks for reporting this issue.
El_A_Tools was previously optimized for the Wien2K code. That is why it is named. This naming will be modified. Go to the **soc** folder and perform the installation process.
