### ISSUE TITLE
How to enter the value of "the (hkl) Miller indices for 2D cut"?

### ISSUE THREAD

**Issue by obaica** [shahramyalameha/ElATools#3]
I gave this value 100, but this didn't work. I tried to enter three 100, the program can run normally. 

I suggest you can give a simple hint here on how to give this value.

**Comment by shahramyalameha** [comment]
Thanks for making this point.
Enter each number with a space. 
correct: 1 0 0  or 1 1 0
not correct: 100 or 110
The reading format of this index is as follows: 
Read(*,*)h, k, l
Therefore, the indices are read separately

**Comment by obaica** [comment]
Thanks, according to your suggestion, it works.
